# Generated by Django 5.0.4 on 2024-04-30 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studapp', '0003_remove_student_enrollment_date_enrollment'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='enrollment_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Enrollment',
        ),
    ]
